//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syinca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_Empresas
    {
        public int Id { get; set; }
        public string Nit { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public int Representante { get; set; }
        public int JfeRecursos { get; set; }
        public int Ciudad { get; set; }
        public int Direccion { get; set; }
        public string TelefonoFijo { get; set; }
        public string NroCelular { get; set; }
        public string Email { get; set; }
        public int NroEmpleados { get; set; }
        public Nullable<int> Latitud { get; set; }
        public Nullable<int> Longitud { get; set; }
        public Nullable<int> Zona { get; set; }
    }
}
