//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syinca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_ServiciosMasSolicitados
    {
        public int Id { get; set; }
        public Nullable<int> Visita { get; set; }
        public Nullable<int> Servicio { get; set; }
    
        public virtual COM_Servicios COM_Servicios { get; set; }
        public virtual COM_Visitas COM_Visitas { get; set; }
    }
}
