//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syinca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_Sucursales
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COM_Sucursales()
        {
            this.COM_Visitas = new HashSet<COM_Visitas>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Ciudad { get; set; }
        public string Direccion { get; set; }
        public string TelefonoFijo { get; set; }
        public string NroCelular { get; set; }
        public Nullable<int> Contacto { get; set; }
        public string Email { get; set; }
        public Nullable<int> NroEmpleados { get; set; }
        public Nullable<int> Latitud { get; set; }
        public Nullable<int> Longitud { get; set; }
        public Nullable<int> Zona { get; set; }
        public Nullable<int> Empresa { get; set; }
    
        public virtual COM_Empresas COM_Empresas { get; set; }
        public virtual COM_Representantes COM_Representantes { get; set; }
        public virtual COM_Zonas COM_Zonas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COM_Visitas> COM_Visitas { get; set; }
    }
}
