//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syinca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COM_Visitas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COM_Visitas()
        {
            this.COM_DetalleVisita = new HashSet<COM_DetalleVisita>();
            this.COM_QuienRecibeVisita = new HashSet<COM_QuienRecibeVisita>();
            this.COM_ServiciosMasSolicitados = new HashSet<COM_ServiciosMasSolicitados>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Representante { get; set; }
        public Nullable<int> Sucursal { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> HoraInici { get; set; }
        public Nullable<System.TimeSpan> HoraFin { get; set; }
        public Nullable<System.TimeSpan> Tiempo { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Objetivo { get; set; }
        public string Estado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COM_DetalleVisita> COM_DetalleVisita { get; set; }
        public virtual COM_ObjetivosVisitas COM_ObjetivosVisitas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COM_QuienRecibeVisita> COM_QuienRecibeVisita { get; set; }
        public virtual COM_RepresantesComerciales COM_RepresantesComerciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COM_ServiciosMasSolicitados> COM_ServiciosMasSolicitados { get; set; }
        public virtual COM_Sucursales COM_Sucursales { get; set; }
    }
}
