//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syinca.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmpresasContext : DbContext
    {
        public EmpresasContext()
            : base("name=EmpresasContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COM_DetalleMeta> COM_DetalleMeta { get; set; }
        public virtual DbSet<COM_DetalleMetaPromocion> COM_DetalleMetaPromocion { get; set; }
        public virtual DbSet<COM_DetalleVisita> COM_DetalleVisita { get; set; }
        public virtual DbSet<COM_Empresas> COM_Empresas { get; set; }
        public virtual DbSet<COM_Finalidades> COM_Finalidades { get; set; }
        public virtual DbSet<COM_Metas> COM_Metas { get; set; }
        public virtual DbSet<COM_ObjetivosVisitas> COM_ObjetivosVisitas { get; set; }
        public virtual DbSet<COM_QuienRecibeVisita> COM_QuienRecibeVisita { get; set; }
        public virtual DbSet<COM_RepresantesComerciales> COM_RepresantesComerciales { get; set; }
        public virtual DbSet<COM_Representantes> COM_Representantes { get; set; }
        public virtual DbSet<COM_Servicios> COM_Servicios { get; set; }
        public virtual DbSet<COM_ServiciosMasSolicitados> COM_ServiciosMasSolicitados { get; set; }
        public virtual DbSet<COM_Sucursales> COM_Sucursales { get; set; }
        public virtual DbSet<COM_Visitas> COM_Visitas { get; set; }
        public virtual DbSet<COM_Zonas> COM_Zonas { get; set; }
    }
}
